"""create users and professors tables

Revision ID: 029f296b109a
Revises: 02e980103866
Create Date: 2025-12-15 01:51:40.714449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029f296b109a'
down_revision: Union[str, Sequence[str], None] = '02e980103866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('professors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.drop_column('professors', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
