"""modified all table 

Revision ID: 16e10463803e
Revises: aea673915c05
Create Date: 2025-12-15 13:12:44.460140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16e10463803e'
down_revision: Union[str, Sequence[str], None] = 'aea673915c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_professor_association_ibfk_2'), 'course_professor_association', type_='foreignkey')
    op.drop_constraint(op.f('course_professor_association_ibfk_1'), 'course_professor_association', type_='foreignkey')
    op.create_foreign_key(None, 'course_professor_association', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course_professor_association', 'professors', ['professor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('course_type_association_ibfk_1'), 'course_type_association', type_='foreignkey')
    op.drop_constraint(op.f('course_type_association_ibfk_2'), 'course_type_association', type_='foreignkey')
    op.create_foreign_key(None, 'course_type_association', 'types', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course_type_association', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('courses_ibfk_1'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fields_ibfk_1'), 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('professors_ibfk_1'), 'professors', type_='foreignkey')
    op.create_foreign_key(None, 'professors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('room_type', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('rooms_ibfk_1'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rooms', 'type')
    op.drop_constraint(op.f('seances_ibfk_5'), 'seances', type_='foreignkey')
    op.drop_constraint(op.f('seances_ibfk_2'), 'seances', type_='foreignkey')
    op.drop_constraint(op.f('seances_ibfk_4'), 'seances', type_='foreignkey')
    op.drop_constraint(op.f('seances_ibfk_1'), 'seances', type_='foreignkey')
    op.drop_constraint(op.f('seances_ibfk_3'), 'seances', type_='foreignkey')
    op.create_foreign_key(None, 'seances', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seances', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seances', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seances', 'professors', ['professor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seances', type_='foreignkey')
    op.drop_constraint(None, 'seances', type_='foreignkey')
    op.drop_constraint(None, 'seances', type_='foreignkey')
    op.drop_constraint(None, 'seances', type_='foreignkey')
    op.drop_constraint(None, 'seances', type_='foreignkey')
    op.create_foreign_key(op.f('seances_ibfk_3'), 'seances', 'professors', ['professor_id'], ['id'])
    op.create_foreign_key(op.f('seances_ibfk_1'), 'seances', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('seances_ibfk_4'), 'seances', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('seances_ibfk_2'), 'seances', 'fields', ['field_id'], ['id'])
    op.create_foreign_key(op.f('seances_ibfk_5'), 'seances', 'users', ['user_id'], ['id'])
    op.add_column('rooms', sa.Column('type', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_ibfk_1'), 'rooms', 'users', ['user_id'], ['id'])
    op.drop_column('rooms', 'room_type')
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.create_foreign_key(op.f('professors_ibfk_1'), 'professors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key(op.f('fields_ibfk_1'), 'fields', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_ibfk_1'), 'courses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'course_type_association', type_='foreignkey')
    op.drop_constraint(None, 'course_type_association', type_='foreignkey')
    op.create_foreign_key(op.f('course_type_association_ibfk_2'), 'course_type_association', 'types', ['type_id'], ['id'])
    op.create_foreign_key(op.f('course_type_association_ibfk_1'), 'course_type_association', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'course_professor_association', type_='foreignkey')
    op.drop_constraint(None, 'course_professor_association', type_='foreignkey')
    op.create_foreign_key(op.f('course_professor_association_ibfk_1'), 'course_professor_association', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('course_professor_association_ibfk_2'), 'course_professor_association', 'professors', ['professor_id'], ['id'])
    # ### end Alembic commands ###
