"""add url to time_tables

Revision ID: 27f352150b0b
Revises: 23800a143018
Create Date: 2025-12-20 15:58:20.548927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f352150b0b'
down_revision: Union[str, Sequence[str], None] = '23800a143018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_tables', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_tables', 'url')
    # ### end Alembic commands ###
