"""modified the foriegn key 

Revision ID: a84d35df04fc
Revises: 16e10463803e
Create Date: 2025-12-15 13:34:25.047033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a84d35df04fc'
down_revision: Union[str, Sequence[str], None] = '16e10463803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fields', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('professors', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('rooms', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('seances', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('seances', 'field_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('seances', 'professor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('seances', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('seances', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seances', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('seances', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('seances', 'professor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('seances', 'field_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('seances', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('rooms', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('professors', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('fields', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('courses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
