from .seance import    Seance
from .user import User
from .course import Course
from .professor import Professor
from .field import Field
from .room import Room
from .type import Type
from .enrollment import Enrollment
from .course_professor import course_professor_association
from .course_field import CourseField
from .time_table import TimeTable
